application: fbpageget
version: 1
runtime: python
api_version: 1
threadsafe: yes

handlers:

- url: /(.+\.php)$
  script: \1

- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

- url: /
  static_files: index.html
  upload: index.html

- url: /([^\.]+)([^/])
  static_files: \1\2/index.html
  upload: (.+)
  
- url: /(.+)
  static_files: \1
  upload: (.+)
  
  
