application: fbpageget
version: 1
runtime: python
api_version: 1
threadsafe: yes

# index files
handlers:

- url: /(.+\.php)$
  script: \1

- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

# site root
- url: /
  static_files: index.html
  upload: index.html

# For folders without trailing slashes - ideally a 301 redirect, but we're static & it isn't 2004
- url: /([^\.]+)([^/])
  static_files: \1\2/index.html
  upload: (.+)
  
  

# Redirect Everything else
- url: /(.+)
  static_files: \1
  upload: (.+)
  
  
